PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  description TEXT,
  group_name TEXT,
  icon TEXT,
  host TEXT,
  url TEXT,
  cf_token TEXT,
  cf_user TEXT,
  deps TEXT,
  notes TEXT,
  status TEXT DEFAULT 'active',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(1,'RoofOS','Complete roofing management SaaS','TopCal Roofing','�Y�-','Cloudflare Pages','https://app.topcalroofing.com','Zkem7ZcfpaiIP53iK0rqcqDEkp5YHbUZBMASdJOU','jesse.topcalroofing@gmail.com','React, Vite, Cloudflare Workers, D1 SQLite, Wrangler','Multi-tenant. React + Vite + CF Workers + D1 SQLite. Staging: ea06a26a.roofos.pages.dev. Worker: topcal-roofing-leads-api.','active','2026-04-13 21:27:42','2026-04-13 21:27:42');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(2,'TopCal Roofing Jobs Map','Track jobs completed on a map','TopCal Roofing','[map]','Cloudflare','https://topcalroofing.com/jobs/index.html','Zkem7ZcfpaiIP53iK0rqcqDEkp5YHbUZBMASdJOU','jesse.topcalroofing@gmail.com',NULL,NULL,'active','2026-04-13 21:27:42','2026-04-13 21:27:42');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(3,'TopCal Roofing Ops','All leads and finance tracker','TopCal Roofing','[ops]','Cloudflare','https://topcalroofing.com/ops/tracker.html',NULL,'jesse.topcalroofing@gmail.com',NULL,NULL,'active','2026-04-13 21:27:42','2026-04-13 21:27:42');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(4,'Topcal My Jobs','Jobs pending dashboard','TopCal Roofing','[jobs]','Cloudflare','https://topcalroofing.com/jobs/myjobs.html',NULL,NULL,NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(5,'Topcal Roof Scout','Find damaged roofs tool','TopCal Roofing','[scout]','Cloudflare Pages','https://main.topcal-roofing.pages.dev/',NULL,NULL,NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(6,'Topcal.net Website','General construction landing page','TopCal Roofing','[web]','Cloudflare Pages','https://topcal-net.pages.dev/',NULL,NULL,NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(7,'Topcal Onboarding','Onboarding for new salespeople','TopCal Roofing','[onboard]','Vercel','https://topcal-onboarding.vercel.app/admin',NULL,NULL,'Vercel, GitHub','GitHub repo: jessetopcalroofing-commits/topcal-onboarding. Clone locally to continue dev.','active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(8,'RoofOS Localhost','Test environment before going live','TopCal Roofing','[local]','Local','C:/Users/jesse/downloads/roofos/LOCAL_DEV.html',NULL,NULL,NULL,'Local dev environment for RoofOS.','active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(9,'RoofOS TopCal CRM','CRM handoff reference','TopCal Roofing','[crm]','Local','file:///C:/Users/jesse/downloads/roofos/HANDOFF.html',NULL,NULL,NULL,'See also HANDOFF-SESSION2.html and PRODUCTION_ARCHITECTURE.html.','active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(10,'Sophia AI Agent','AI agent configuration tool','TopCal Roofing','[ai]','Local','file:///C:/Users/jesse/Downloads/PROJECTS/RoofOS/Localhost/sophia-config.html',NULL,NULL,NULL,'Local config tool for Sophia AI agent.','active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(11,'Barterflip','Service exchange marketplace','Side Projects','[swap]','Cloudflare Pages','https://barterflip.pages.dev/','Zkem7ZcfpaiIP53iK0rqcqDEkp5YHbUZBMASdJOU','jesse.topcalroofing@gmail.com',NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(12,'FinanceIQ','Personal and business forecast tool','Side Projects','[finance]','Cloudflare Pages','https://financeiq-ccn.pages.dev/','d5jvyI5JDmW2gKtxjN_9gcbYgbzXCKn1ETDffROi','jesse.topcalroofing@gmail.com',NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(13,'VibeTrack','Vibe coding productivity tool','Side Projects','[vibe]','Cloudflare Pages','https://vibetrack-app.pages.dev/','rTpFaQX17QLAtMEjD4ygd7TfsURo6oRa3Vf7nUWj','jesse.topcalroofing@gmail.com',NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(14,'SkillBridge','Marketplace to find mentors','Side Projects','[skills]','Cloudflare Pages','https://skillsbridge.pages.dev/','Aq4Q5vWj_Lf90_eE-6Bx8JyxhA6WP1cXvkusdETR','jesse.topcalroofing@gmail.com',NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(15,'FocusQuest','Task and goal tracker app','Side Projects','[focus]','Cloudflare Pages','https://focusquest-c3j.pages.dev/app',NULL,NULL,NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(16,'Jextera','Parent company website','Side Projects','[corp]','Cloudflare (static)','https://jextera.com/',NULL,'jesse.topcalroofing@gmail.com',NULL,'Static site hosted on Cloudflare.','active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(17,'Claros For Council 2026','Political campaign website','Political / Community','[vote]','Cloudflare Pages','https://barterflip.pages.dev/claros-for-cd1',NULL,NULL,NULL,'Raul Claros campaign site. Mobile nav in progress.','active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(18,'California Rising Page','Nonprofit donation page','Political / Community','[ca]','Netlify','https://brilliant-puffpuff-c71164.netlify.app/#donate',NULL,NULL,NULL,NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(19,'Claros Volunteer Form','Sign-up form from Raul''s website','Political / Community','[form]','Google Forms','https://docs.google.com/forms/d/1lzb4IcKWFcLZVKlDdk08_BjZsXcTUjRiEjGzCG0veug/edit',NULL,NULL,'Google Forms',NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(20,'Claros Volunteer Responses','Volunteer signups spreadsheet','Political / Community','[sheet]','Google Sheets','https://docs.google.com/spreadsheets/d/12txZzTATSxbYhkKsIAI6jmhzb48kX1zhNEkuoT-YqAg/edit',NULL,NULL,'Google Sheets',NULL,'active','2026-04-13 21:27:43','2026-04-13 21:27:43');
INSERT INTO "projects" ("id","name","description","group_name","icon","host","url","cf_token","cf_user","deps","notes","status","created_at","updated_at") VALUES(21,'Project Hub','Project tracker and dependency manager','Side Projects','[hub]','Cloudflare Pages','https://project-hub-4qm.pages.dev',NULL,'jesse.topcalroofing@gmail.com','Cloudflare Workers, D1 SQLite, Wrangler',replace('Worker: project-hub-api.jesse-topcalroofing.workers.dev. Deploy with: powershell -ExecutionPolicy Bypass -File C:/Users/jesse/Downloads/deploy.ps1\n\n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','\n',char(10)),'active','2026-04-13 23:27:59','2026-04-14 01:15:46');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('projects',21);
